// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwb-eNgFksiViIlYqazbO3A-ypntCVdTs',
    appId: '1:196487528123:web:5d7e774aaee5389a22739e',
    messagingSenderId: '196487528123',
    projectId: 'phcapp-525c3',
    authDomain: 'phcapp-525c3.firebaseapp.com',
    storageBucket: 'phcapp-525c3.firebasestorage.app',
    measurementId: 'G-TBBVNFXGVE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX_SCjnP4abTH_Va2jnjpUYVYYnzr2MKU',
    appId: '1:196487528123:android:a5e2b7a613d597ff22739e',
    messagingSenderId: '196487528123',
    projectId: 'phcapp-525c3',
    storageBucket: 'phcapp-525c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqGPJLpjLOfAJrKyisyYDTnD2S8IZ-qaU',
    appId: '1:196487528123:ios:048bbfbf10eeb56622739e',
    messagingSenderId: '196487528123',
    projectId: 'phcapp-525c3',
    storageBucket: 'phcapp-525c3.firebasestorage.app',
    iosClientId: '196487528123-qf7vvfl188h4hsvgaft442chj0kfls6c.apps.googleusercontent.com',
    iosBundleId: 'com.example.hospitalapps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqGPJLpjLOfAJrKyisyYDTnD2S8IZ-qaU',
    appId: '1:196487528123:ios:563c7df12cec5f1922739e',
    messagingSenderId: '196487528123',
    projectId: 'phcapp-525c3',
    storageBucket: 'phcapp-525c3.firebasestorage.app',
    iosClientId: '196487528123-befqhco6c7p1bo9e6jtk9kn3qkb7ec9i.apps.googleusercontent.com',
    iosBundleId: 'com.example.hospitalapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwb-eNgFksiViIlYqazbO3A-ypntCVdTs',
    appId: '1:196487528123:web:584d0038315d3e4b22739e',
    messagingSenderId: '196487528123',
    projectId: 'phcapp-525c3',
    authDomain: 'phcapp-525c3.firebaseapp.com',
    storageBucket: 'phcapp-525c3.firebasestorage.app',
    measurementId: 'G-59XHWWPW5S',
  );

}